### ISSUE TITLE
Issue with importing script

### ISSUE THREAD

**Issue by karanrajpal14** [rovellipaolo/NinjaDroid#1]
I'd like to use your project to work on a script I'd use personally. Unfortunately, since the package and the script have the same name, I'm unable to do so. And python 3 doesn't allow relative imports so I'm not able to do much. I just want to use the functions provided in ninjadroid.py. Any remedy for this?

**Comment by rovellipaolo** [comment]
I am running it using Python 3 without any issue.
Anyway, the code is open source. Feel free to change it as you please, and to submit me a pull request.
