### ISSUE TITLE
Dockerfile structure doesn't make good use of layer caching

### ISSUE THREAD

**Issue by iantruslove** [rovellipaolo/NinjaDroid#13]
Because we're copying in the entire build directory ([here](https://github.com/rovellipaolo/NinjaDroid/blob/ce1b3057f5dad35d790c1869aa3bc935bb45649d/Dockerfile#L25)) any changes to any of the files in the project will bust Docker's build cache. 

Splitting the `ADD`s up into a few more pieces and taking action based only on changes introduced by that `ADD` mean Docker can better optimize build times by eliminating unnecessary steps. The "cost" of additional `ADD`s is more layers in the image, but the layers are independent so there's no real net negative (versus layers which significantly alter underlying layers which unnecessarily increases the total image size).

**Comment by rovellipaolo** [comment]
Fixed with your pull request: https://github.com/rovellipaolo/NinjaDroid/pull/14/
