### ISSUE TITLE
JobExectutor isn't asynchronous

### ISSUE THREAD

**Issue by iantruslove** [rovellipaolo/NinjaDroid#15]
I'm not quite sure what to do about this one...

The problem is that none of the async stuff is actually async because none of the ThreadPoolExecutor invocations are with callables, they're all with the result of actually calling the "work" functions.

For example, [here](https://github.com/rovellipaolo/NinjaDroid/blob/739a496cdfec977561713f2444940bec501474de/ninjadroid/use_cases/launch_dex2jar.py#L34):

`os.system(command)` is run and its result captured before being sent to the executor's submit method.

To actually call this and have it run asynchronously, you could do it e.g. with a little tweak  to [JobExecutor](https://github.com/rovellipaolo/NinjaDroid/blob/739a496cdfec977561713f2444940bec501474de/ninjadroid/concurrent/job_executor.py)

```python
class JobExecutor:
    # ...
    def submit(self, fn, *args, **kwargs) -> Future:
        return self.executor.submit(fn, *args, **kwargs)
```

then work to be done in the threadpool gets called by passing in a callable, plus any args, e.g. using the earlier example:

```python
class LaunchDex2Jar(UseCase):
    # ...
    def execute(self) -> Future:
        # ...
        command = LaunchDex2Jar.DEX2JAR + " -f " + self.input_filepath + \
                  " -o " + self.output_directory + "/" + jarfile

        return self.executor.submit(os.system, command)
```

But here's the tricky bit... If you do this, there are new issues, most obviously (1) waiting for all the futures in a group to finish, and (2) the very real possibility of race conditions.

I'm not sure how you'd like to proceed with this. I'd be tempted to simply rip out all the executor stuff because it's effectively just dead code not providing any benefit. Happy to lend a hand if you have any thoughts...

**Comment by rovellipaolo** [comment]
You are totally right. However, I'm still not totally sure on what to do with this.

From one side, yes, we could execute everything synchronously and get rid of the _JobExecutor_.
Most of the jobs have dependencies with another one and must be executed in a chain-fashion one after the other anyway (e.g. see _ExtractApkEntries_).

However, some of the jobs could actually be executed in parallel (e.g. _GetApkInfoInHtml_ and _GetApkInfoInJson_) and, by using _Future_, we could chain them easily.

**Comment by rovellipaolo** [comment]
Finally, I had some spare time and I've decided to remove the _JobExecutor_ and execute the use cases synchronously: https://github.com/rovellipaolo/NinjaDroid/commit/1ebf316f70b0a299cfde7a1d3d559700ca444edd
