### ISSUE TITLE
Getting syntax error

### ISSUE THREAD

**Issue by tasQ23** [rovellipaolo/NinjaDroid#2]
Hi, I am getting this error whenever I try to run ninjadroid with this command 
"python ninjadroid.py com.gh4a-46.apk" :

> File "ninjadroid.py", line 68
>     def read_target_file(filepath: str, no_string_processing: bool):
>                                                  
> SyntaxError: invalid syntax
> 

(The arrow pointer is directly under the colon which I cannot show here).
I did not change anything in the given python file. I cannot see where the issue is either. It seems fine to me, yet giving the error.

**Comment by tasQ23** [comment]
I found the issue, I needed to update my python version to 3. ^_^

**Comment by rovellipaolo** [comment]
Sorry for reading this only now. Thanks for reporting it! :)
