### ISSUE TITLE
multidex support

### ISSUE THREAD

**Issue by huuck** [rovellipaolo/NinjaDroid#7]
Hello!

Looks like right now only the "classes.dex" file is being parsed :( Are there any plans to implement support for APKs that have multiple dex files inside?

Kindest regards,
Gabriel

**Comment by rovellipaolo** [comment]
Hello! (and sorry for the late response)

Yes, that is something that should be done.
But, unfortunately, at the moment I've no time to work on this.

That said, if you're willing and have time to do it and send me a pull request, I'll try to find a spot to review and merge it. :)
